apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: example/cuup-example
  name: cuup-example
  namespace: oai-ran-cuup
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|example|cuup-example'
spec:
  provider: cuup.openairinterface.org
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cuup-nf-config
