apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata: # kpt-merge: upf-example/oai-upf-config
  name: oai-upf-config
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFConfig|upf-example|oai-upf-config'
spec:
  configRefs:
  - apiVersion: cellular.nephio.org/v1alpha1
    kind: PLMN
    metadata:
      name: oai-plmn
    spec:
      plmnInfo:
      - plmnID:
          mcc: "001"
          mnc: "01"
        tac: 1
        nssai:
        - sst: 1
          sd: ffffff
          dnnInfo:
          - name: internet
            sessionType: ipv4
            dns: 8.8.8.8
            subnet: 10.1.0.0/24
